---
- name: Install libselinux-python
  yum: name=libselinux-python state=latest

- stat: path=/etc/yum.repos.d/epel.repo
  register: epel_installed

- name: Install epel repositry
  yum: name=http://ftp.iij.ad.jp/pub/linux/fedora/epel/6/x86_64/epel-release-6-8.noarch.rpm
  when: not epel_installed.stat.exists

- replace: dest=/etc/yum.repos.d/epel.repo regexp="enabled *= *1" replace="enabled=0"
